-- Basic config
require("core.commands")
require("core.plugins")
require("core.configs")
require("core.mappings")
require("core.lsp")
-- Toolkit (is a other useful functions)
require('toolkit.generate')
require('toolkit.files_dap')
require('toolkit.env')
-- Plugins config
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.buffline")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.illuminate")
require("plugins.dap")
require("plugins.kanagawa")
require("plugins.color-picker")
require("plugins.defaults")
require("plugins.bookmarks")
require("plugins.autopairs")
require("plugins.notify")
require("plugins.dbee")
require("plugins.tagger")
