return {
    cmd = { "gopls" },
    filetypes = { "go", "gomod", "gowork", "gotmpl" },
    settings = {
        gopls = {
            buildFlags = { "-tags=integration" },
            staticcheck = true,
            analyses = {
                unusedparams = true,
                shadow = true,
                unusedwrite = true,
                unreachable = true,
                nilerr = true,
                copylocks = true,
                atomic = true,
                loopclosure = true,
                printf = true,
                defervalue = true,
            },
            usePlaceholders = true,
            completeUnimported = true,
            matcher = "fuzzy",
            symbolMatcher = "fuzzy",
            experimentalPostfixCompletions = true,
            hints = {
                assignVariableTypes = true,
                compositeLiteralFields = true,
                compositeLiteralValues = true,
                constantValues = true,
                functionTypeParameters = true,
                parameterNames = true,
                rangeVariableTypes = true,
            },
        },
    },
}
